modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="axe_or_ex"
version="1.0.0"
displayName="Axe Or Ex"
authors="Emtypyie"
description='''
Adds throwable axes with charge system and heavy damage.
'''

[[dependencies.axe_or_ex]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.axe_or_ex]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
